# Memoria disponivel para o Gradle.
org.gradle.parallel=true

# IntelliJ IDEA ainda nao e totalmente compativel com o configuration cache do Loom.
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric / Minecraft — conferir em https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19

# Propriedades do mod
version=0.1.1
group=com.bedrockux
archives_base_name=bedrockux

# Dependencias
fabric_api_version=0.158.0+26.2
